### ISSUE TITLE
records are being saved with the entire path as the file name

### ISSUE THREAD

**Issue by ShaunOfTheLive** [wardellchandler/HangoutsBot#17]
There are files in the main HangoutsBot directory that are named, for example, "Records\UgzF8k8Rv1ojeCgbbGN4AaABAQ\2015-03-10.txt", instead of being saved under a Records directory.

**Comment by wardellbagby** [comment]
@ShaunOfTheLive What OS are you using?

**Comment by ShaunOfTheLive** [comment]
Debian Linux 7.0.

**Comment by wardellbagby** [comment]
@ShaunOfTheLive I'm pretty sure that this issue is because I was manually joining directory names and using '\' instead of using os.path.join, so it's probably a pretty easy fix, but I'm going to test this on my Box later today to make sure that that's it.

**Comment by ShaunOfTheLive** [comment]
This bug is still present in Core/Bot.py in the handle_rename() function.
