### ISSUE TITLE
Detect when bot account is added/leaves a conversation

### ISSUE THREAD

**Issue by cntrlwiz** [wardellchandler/HangoutsBot#25]
Is there a way to detect when the bot is added to an existing conversation?
I would also like to detect if the account leaves a conversation, outside of /leave.

**Comment by wardellbagby** [comment]
Well, yes and no. If you add in "membership_watching_enabled": true to your config.json file, it'll post events for that, but as of right now, it's set to automatically ignore the Bot's adding and removal from a chat. 

However, if you check the method def handle_membership_change(self, conv_event) in the Bot.py file, you can delete that is_self check and then it should work fine.
