### ISSUE TITLE
Bot non-responsive since last update.

### ISSUE THREAD

**Issue by SeeJayEmm** [wardellchandler/HangoutsBot#7]
I can't exactly say which commit as HangoutsBot was running for some time without a restart. But since I've restarted it, it's completely non-responsive.  It appears to be connecting OK just not responding to any commands. I've done the following:
1. Logged into the account and verified all is working.
2. Cloned a clean copy of the repo and re-logged in.
3. Deleted/Left all conversations to start over from scratch.

After 3 I logged it back in and attempted a /ping.  This is all I see:

```
Already up-to-date.
Connected!
Conversations:

Received ClientSetTypingNotification for unknown conversation Ugz7JPyrXNtBDMemOw14AaABAQ
```

The log.txt file is empty.

I'm using your sample config.json from the Readme. The only change is I put my email address in the admins variable.

I did verify that the hangout invite was accepted. I'm also able to add it to other hangouts and have him auto-accept. It just doesn't respond to any queries.

**Comment by wardellbagby** [comment]
Interesting.

I realize now that I wasn't clear about this, but in the "admins" variable in the config, that should be your user-id, not your email address. The easiest way to get it is generally by running the /user your-name-here command, and it'll tell you.

You can try removing the admins array entirely and see what that gets you. 

The "ClientSetTypingNotification" error is telling you that the Bot doesn't recognize that conversation, which makes sense if you had it leave all conversations.

So yeah, try removing the admins array entirely. If that doesn't work, try manually replying from the bot's account in Gmail to double-check that the Bot is allowing that conversation. 

If that still does nothing, come back and we'll figure this out.

**Comment by SeeJayEmm** [comment]
Fair enough. Unfortunately since it won't talk to me I can't get a response
on the /user command.

I've removed the admins array, nothing.

I am able to log in on the bot's account and respond to my own messages.

The ClientSetTypingNotification was a one time item. Also when I start the
bot now I get see the following:
Already up-to-date.
Connected!
Conversations:
  Chris Michaels (Ugz7JPyrXNtBDMemOw14AaABAQ)

So it recognizes our conversation.

I tried adding that conversation to the config. That did nothing.

On Wed, Feb 25, 2015 at 12:36 PM, Wardell Bagby notifications@github.com
wrote:

> Interesting.
> 
> I realize now that I wasn't clear about this, but in the "admins" variable
> in the config, that should be your user-id, not your email address. The
> easiest way to get it is generally by running the /user your-name-here
> command, and it'll tell you.
> 
> You can try removing the admins array entirely and see what that gets you.
> 
> The "ClientSetTypingNotification" error is telling you that the Bot
> doesn't recognize that conversation, which makes sense if you had it leave
> all conversations.
> 
> So yeah, try removing the admins array entirely. If that doesn't work, try
> manually replying from the bot's account in Gmail to double-check that the
> Bot is allowing that conversation.
> 
> If that still does nothing, come back and we'll figure this out.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wardellchandler/HangoutsBot/issues/7#issuecomment-76013481
> .

## 

## Chris

_Peace and Humptiness forever._

**Comment by wardellbagby** [comment]
This behavior makes me think that maybe the Bot has blocked you, but that shouldn't be persisting through-out a restart. Let me look deeper into this.

**Comment by wardellbagby** [comment]
What happens if you say "Hello, Bot."?

**Comment by SeeJayEmm** [comment]
Absolutely nothing. :(  I am also logged into the account in my browser and
I can see the msgs coming through.

On Wed, Feb 25, 2015 at 2:05 PM, Wardell Bagby notifications@github.com
wrote:

> What happens if you say "Hello, Bot."?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wardellchandler/HangoutsBot/issues/7#issuecomment-76032129
> .

## 

## Chris

_Peace and Humptiness forever._

**Comment by wardellbagby** [comment]
Just to double check, paste the entirety of your config.json here, removing your ID code in the admins array.

**Comment by SeeJayEmm** [comment]
I deleted the admins array as per your direction.

chris@saffron:~/HangoutsBot$ more config.json
{
  "autoreplies_enabled": true,
  "autoreplies": [
    [["bot", "robot", "Yo"], "/think {}"]
  ],
  "development_mode": false,
  "commands_admin": ["hangouts", "reload", "quit", "restart", "config",
"restart
", "block"],
  "commands_enabled": true,
  "forwarding_enabled": false,
  "rename_watching_enabled": true,
  "conversations": {
    "Ugz7JPyrXNtBDMemOw14AaABAQ": {
      "autoreplies": [
        [["whistle", "bot", "whistlebot"], "/think {}"],
        [["trash"], "You're trash"]
      ]
    }
  }
}

On Wed, Feb 25, 2015 at 4:25 PM, Wardell Bagby notifications@github.com
wrote:

> Just to double check, paste the entirety of your config.json here,
> removing your ID code in the admins array.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wardellchandler/HangoutsBot/issues/7#issuecomment-76063390
> .

## 

## Chris

_Peace and Humptiness forever._

**Comment by wardellbagby** [comment]
Alright, I can't find anything immediately. Can you tell me the date the file Main.py was created on your box? Should give me an idea which commit might've caused the problem, as that file wasn't moved doing the refactor I did.

**Comment by SeeJayEmm** [comment]
Feb 25 12:07 Main.py

As I said this is a brand new clone of the repo.  Could there be an issue
with one of my Python packages? Do you know what your dependencies are I
can compare that to what I have installed?

On Wed, Feb 25, 2015 at 4:44 PM, Wardell Bagby notifications@github.com
wrote:

> Alright, I can't find anything immediately. Can you tell me the date the
> file Main.py was created on your box? Should give me an idea which commit
> might've caused the problem, as that file wasn't moved doing the refactor I
> did.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wardellchandler/HangoutsBot/issues/7#issuecomment-76067016
> .

## 

## Chris

_Peace and Humptiness forever._

**Comment by wardellbagby** [comment]
Right; I forgot you said that.

I need to compile a list of dependencies. I believe these are all that it
needs, though:

aiohttp
appdirs
argparse
asyncio
beautifulsoup4
dateutils
enum34
hangups
hangups-robobrowser
hangups-urwid
httplib2
purplex
python-dateutil
pytz
requests
six

**Comment by SeeJayEmm** [comment]
I was lacking the following:
argparse
dateutils
httplib2
pytz

Unfortunately no change after installing them.

**Comment by SeeJayEmm** [comment]
In the process of going through your list of requirements I updated everything I could (via pip) except requests. There's an issue with the latest requests that pip pulls down that breaks on my system, but this isn't anything new. For what it's worth I'm running Ubuntu 14.10 and Python 3.4.2.

I went through my nightly backups and found the what _was_ the last working version. The main.py was dated Feb 5. I am no longer able to run that version though. Maybe related to some of the python packages I updated.

**Comment by tdryer** [comment]
What version of hangups do you have installed? This sounds similar to an issue I added a workaround for a while ago: https://github.com/tdryer/hangups/issues/58

You can rule out HangoutsBot by trying with the hangups client directly.

**Comment by SeeJayEmm** [comment]
hangups (0.2.6)
hangups-robobrowser (0.5.2)
hangups-urwid (1.2.2-dev)

On Wed, Feb 25, 2015 at 9:42 PM, Tom Dryer notifications@github.com wrote:

> What version of hangups do you have installed? This sounds similar to an
> issue I added a workaround for a while ago: tdryer/hangups#58
> https://github.com/tdryer/hangups/issues/58
> 
> You can rule out HangoutsBot by trying with the hangups client directly.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wardellchandler/HangoutsBot/issues/7#issuecomment-76112410
> .

## 

## Chris

_Peace and Humptiness forever._

**Comment by SeeJayEmm** [comment]
I tested using the hangups client directly and that worked.​ I had a pleasant conversation with myself.

```
(15-02-26 10:28:30 AM) Adelbert: This is a test
(10:28:55 AM) Chris: Are you sure this is only a test?
(10:29:05 AM) Adelbert: I'm absolutely positive this is only a test.
(10:29:15 AM) Chris: Great I'm glad to hear that.
```

**Comment by wardellbagby** [comment]
I haven't tested on Ubuntu (or any Linux distro) at all, but I'm going to try to do that this weekend, see if maybe it's an OS specific bug.

**Comment by SeeJayEmm** [comment]
I just tested this on a clean Ubuntu 14.10 install (I spun up the VM for other reasons). I'm having the same problem there.

When you test on Ubuntu be aware that python3 is not the default. You'll need to use "pip3" (sudo apt-get install python3-pip) to install packages and exec the bot with "python3 Main.py".

If there's any additional debugging I can do to help, please let me know.

**Comment by bpear** [comment]
Latest bot isn't responding for me too. It starts up fine but does not respond to any commands or the word bot.

**Comment by wardellbagby** [comment]
Are you also on Ubuntu, or any other Linux distro? If so, what name and
version?

**Comment by wardellbagby** [comment]
I know what the problem is, and I'm embarrassed that it took me this long to figure it out. 

It's looking for the config.json file, but it can't find it, but it doesn't actually care, so it defaults to a blank one, which will return false for every query it wants.

But you have a valid config.json file. The problem is that I changed the location it looks for the config.json file in to /Core/, and didn't actually update my readme to say that. I've been meaning to update the logic to check both folders, I just haven't gotten around to it.

So, if you both move your config.json and cookies.txt file from the root folder to the Core folder, you should find that it works fine now. 

Report back and let me know.

**Comment by SeeJayEmm** [comment]
That worked.  Thanks.
